config/routes.rb
Questionnaire::Application.routes.draw do

  resources :forms
  

end

app/models/form.rb
class Form < ActiveRecord::Base
  attr_accessible :email, :name

  validates :name, presence: true, length: { minimum: 2 }
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  def index
  	# This is a comment
  	@name = "matt"
  	@location = "Clerk"
  	@now = Time.now
  	# @message = "Welcome to " + @location + ", " + @name
  	@message = "Welcome to #{@location}, #{@name}"

  	#This is an array
  	@list = ["Matt", "amelia", "Tim", "Calum"]

  	@competition_won_by_sev = true

  	@sev_votes = rand(100)
  	@mark_votes = rand(100)

  	if @sev_votes > @mark_votes
  		@list << "Sev"

  	elsif @sev_votes == @mark_votes
  		@list << "Sev"
  		@list << "Mark"
  	else
  		@list << "Mark"

  	end

  	@forms = Form.all


  end

  def show
  	@form = Form.find(params[:id])
  end

  def new
  	@form = Form.new
  end

  def create
  	@form = Form.new(params[:form])

  	if @form.save
      # Add this message to the next page.
      flash[:success] = "Yay, you've added a response!"

  	redirect_to forms_path
     else
      render "new"
    end
  end

  def edit 
    @form = Form.find params[:id]
  end

  def update
    @form = Form.find params[:id]

    if @form.update_attributes(params[:form])
      redirect_to form_path(@form)
    else
      render "edit"
    end
  end
  
  def destroy
    @form = Form.find params[:id]
    @form.destroy
    redirect_to forms_path
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<%= simple_form_for @form do |f| %>
	<%= f.input :name, label: "Your name" %>
	<%= f.input :email, label: "Email address" %>
	<%= f.button :submit, button %>
<% end %>

app/views/forms/edit.html.erb
<h1>Edit form</h1>

<%= render partial: "form" %>

app/views/forms/index.html.erb
<h1>Hello World</h1>

<%= "my name is Matt".titleize.gsub("a", "4").split(" ") %>

<p> <%= @message  %></p>

<h2>Competition</h2>

<ul>
	<li>Sev got <%= @sev_votes %> votes </li>
	<li> mark got <%= @mark_votes %> votes </li>
<h2>Steer is <%= @list.size %> people:</h2>

<ul>
	<% @list.each do |person| %>

		<li>Person: <%= person %></li>

	<% end %>

<h2>Form responses<h2>

<ul> 
	<% @forms.each do |response| %>

		<li><%= link_to response.name, form_path(response) %></li>

	<% end %>

</ul>	

<p><%= link_to "New response", new_form_path %></p>

app/views/forms/new.html.erb
<h1>New form</h1>

<%= render partial: "form", locals: { button: "Add response" } 
	%>

app/views/forms/show.html.erb
<h1><%= @form.name %></h1>

<p><%= @form.email %></p>

<p><%= link_to "All responses", forms_path %></p>

<p><%= link_to "Edit", edit_form_path(@form) %></p>

<p><%= link_to "Delete", form_path(@form), method: :delete %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Questionnaire</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>

<header>
	<h1>Wufoo!</h1>
</header>


<% if flash.any? %>
	<div style="background: green;"><%= flash[:success] %></div>
<% end %>

<%= yield %>

<footer>
	&copy; 2013

</footer>

</body>
</html>